# Generated by Django 3.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='day_name',
        ),
        migrations.AddField(
            model_name='friend',
            name='data',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]